version: '3'

services:
  alert_handler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    command: python -m alert_handler
  packet_sniffer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    command: python -m packet_sniffer
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    command: python -m server

