version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-python-app:latest
    container_name: python-app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python server.py
    depends_on:
      - db
      - redis

  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
